 # Generated by Django 3.0.2 on 2020-05-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('orientation', models.TextField()),
                ('hometown', models.TextField()),
                ('major', models.TextField()),
            ],
        ),
    ]
