# Generated by Django 3.0.2 on 2020-05-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowers',
            name='hometown',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='rowers',
            name='major',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='rowers',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='rowers',
            name='orientation',
            field=models.CharField(max_length=64),
        ),
    ]
