# Generated by Django 3.0.2 on 2020-05-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0002_auto_20200506_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowers',
            name='picture',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='rowingWebsiteApp/static/rowerPictures/'),
        ),
    ]
