# Generated by Django 3.0.2 on 2020-05-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0003_rowers_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowers',
            name='picture',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='rowingWebsiteApp/media/rowers/'),
        ),
    ]
