# Generated by Django 3.0.2 on 2020-05-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0004_auto_20200506_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowers',
            name='picture',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='rowingWebsite/rowingWebsiteApp/media/'),
        ),
    ]
