# Generated by Django 3.0.2 on 2020-05-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0005_auto_20200506_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowers',
            name='crew',
            field=models.CharField(choices=[('Mens', 'Mens'), ('Womens', 'Womens')], default='-----', max_length=64),
        ),
        migrations.AddField(
            model_name='rowers',
            name='varsity',
            field=models.CharField(choices=[('Yes', 'T'), ('No', 'F')], default='-----', max_length=64),
        ),
        migrations.AlterField(
            model_name='rowers',
            name='orientation',
            field=models.CharField(choices=[('Starboard', 'Starboard'), ('Port', 'Port'), ('Bisweptual', 'Bisweptual'), ('Coxswain', 'Coxswain')], max_length=64),
        ),
    ]
