# Generated by Django 3.0.2 on 2020-05-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0010_auto_20200506_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('date_and_time', models.CharField(default='To Be Announced', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('picture', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='rowingWebsite/rowingWebsiteApp/media/')),
                ('writeUp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('date', models.CharField(max_length=64)),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], max_length=64)),
                ('results', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameModel(
            old_name='Rowers',
            new_name='Rower',
        ),
    ]
