# Generated by Django 3.0.2 on 2020-05-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0011_auto_20200507_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='race',
            new_name='name',
        ),
    ]
