# Generated by Django 3.0.2 on 2020-05-10 04:47

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0013_auto_20200509_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '5x7', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='rower',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '5x7', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
