# Generated by Django 3.0.2 on 2020-05-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0014_auto_20200510_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='staff',
            field=models.CharField(choices=[('Officer', 'Officer'), ('Coach', 'Coach')], default='Officer', max_length=64),
        ),
    ]
