# Generated by Django 3.0.2 on 2020-05-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0015_leadership_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_and_time',
            new_name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(default='', max_length=64),
        ),
    ]
