# Generated by Django 3.0.2 on 2020-05-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0016_auto_20200510_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rower',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='rower',
            name='year',
            field=models.CharField(choices=[('Freshmen', 'FR'), ('Sophomore', 'SO'), ('Junior', 'JR'), ('Senior', 'SR')], max_length=64),
        ),
    ]
