# Generated by Django 3.0.2 on 2020-05-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0017_auto_20200512_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadership',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='leadership',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
