# Generated by Django 3.0.2 on 2020-05-12 08:19

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0018_auto_20200512_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '5x5', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
