# Generated by Django 3.0.2 on 2020-05-15 06:18

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0022_gallery_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cropped_image',
            field=image_cropping.fields.ImageRatioField('photo2', '7x5', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropped image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pre-image'),
        ),
    ]
