# Generated by Django 3.0.2 on 2020-05-15 06:22

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0023_auto_20200515_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='cropped_image',
            field=image_cropping.fields.ImageRatioField('image', '7x5', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropped image'),
        ),
    ]
