# Generated by Django 3.0.2 on 2020-05-15 09:03

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0024_auto_20200515_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery', verbose_name='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='cropped_image',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('imagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rowingWebsiteApp.ImageModel')),
                ('title', models.CharField(default='Picture', max_length=64)),
            ],
            bases=('rowingWebsiteApp.imagemodel',),
        ),
        migrations.CreateModel(
            name='Gallery2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gallery', max_length=64)),
                ('photos', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='rowingWebsiteApp.Gallery')),
            ],
        ),
    ]
