# Generated by Django 3.0.2 on 2020-05-15 09:14

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0025_auto_20200515_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='imagemodel_ptr',
        ),
        migrations.AlterField(
            model_name='gallery2',
            name='photos',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='rowingWebsiteApp.Gallery'),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
