# Generated by Django 3.0.2 on 2020-05-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0027_auto_20200516_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='pre-image'),
        ),
    ]
