# Generated by Django 3.0.2 on 2020-05-16 01:45

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0029_auto_20200516_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='photos',
        ),
        migrations.AddField(
            model_name='gallery',
            name='images',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='rowingWebsiteApp.Picture'),
        ),
    ]
