# Generated by Django 3.0.2 on 2020-05-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0030_auto_20200516_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rower',
            options={'ordering': ['last_name']},
        ),
        migrations.RenameField(
            model_name='rower',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='rower',
            name='last_name',
            field=models.CharField(default='-', max_length=64),
        ),
    ]
