# Generated by Django 3.0.2 on 2020-05-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0031_auto_20200516_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
    ]
