# Generated by Django 3.0.2 on 2020-05-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0032_auto_20200516_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='picture',
            field=models.ImageField(upload_to='rowingWebsite/rowingWebsiteApp/media/'),
        ),
        migrations.AlterField(
            model_name='rower',
            name='picture',
            field=models.ImageField(upload_to='rowingWebsite/rowingWebsiteApp/media/'),
        ),
    ]
