# Generated by Django 3.0.2 on 2020-05-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0033_auto_20200517_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(),
        ),
    ]
