# Generated by Django 3.0.2 on 2020-05-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0037_auto_20200517_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
