# Generated by Django 3.0.2 on 2020-05-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0038_auto_20200517_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(default='Event', max_length=64),
        ),
    ]
