# Generated by Django 3.0.2 on 2020-05-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0039_auto_20200517_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
