# Generated by Django 3.0.2 on 2020-05-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0040_auto_20200517_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
    ]
