# Generated by Django 3.0.2 on 2020-05-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0041_remove_event_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='race',
            name='results',
            field=models.CharField(default='', max_length=256),
        ),
    ]
