# Generated by Django 3.0.2 on 2020-05-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0042_auto_20200517_0812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-date'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AddField(
            model_name='picture',
            name='asociated_event',
            field=models.CharField(default='Picture', help_text='Source of the event', max_length=64),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(help_text='Name for the gallery', max_length=64),
        ),
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.CharField(default='Picture', help_text='Describe your images so they can easily be identified to be added into appropriate gallery ', max_length=64),
        ),
        migrations.AlterField(
            model_name='race',
            name='results',
            field=models.CharField(default='-', max_length=256),
        ),
    ]
