# Generated by Django 3.0.2 on 2020-05-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0043_auto_20200517_0851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponsors',
            new_name='Sponsor',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, help_text='Select a date from the picker.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Event address ex: 3355 Dalrymple Dr, Baton Rouge, LA 70802', max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(help_text='Example: 3pm - 5pm', max_length=64),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(help_text='Date the event occured'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='writeUp',
            field=models.TextField(help_text='This will be the text that get displayed under the officer'),
        ),
        migrations.AlterField(
            model_name='race',
            name='location',
            field=models.CharField(help_text='Event address ex: 3355 Dalrymple Dr, Baton Rouge, LA 70802', max_length=64),
        ),
        migrations.AlterField(
            model_name='race',
            name='results',
            field=models.CharField(default='-', help_text='Put the link to regatta central here once', max_length=256),
        ),
        migrations.AlterField(
            model_name='rower',
            name='hometown',
            field=models.CharField(help_text='Example: Baton Rouge, LA', max_length=64),
        ),
    ]
