# Generated by Django 3.0.2 on 2020-05-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0045_auto_20200518_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
    ]
