# Generated by Django 3.0.2 on 2020-05-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0047_homepage_recruitmentpage_sponsorpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-date'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name_plural': 'Home Page Entries'},
        ),
        migrations.AlterModelOptions(
            name='recruitmentpage',
            options={'verbose_name_plural': 'Recruitment Page Entries'},
        ),
        migrations.AlterModelOptions(
            name='sponsorpage',
            options={'verbose_name_plural': 'Sponsor Page Entries'},
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='race',
            name='results',
            field=models.TextField(help_text='List Event Results Here'),
        ),
    ]
