# Generated by Django 3.0.2 on 2020-05-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0048_auto_20200521_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('text', models.TextField(help_text='This will be the text that gets displayed')),
                ('image', models.ImageField(upload_to='template_photos')),
            ],
            options={
                'verbose_name_plural': 'About Us Page Entries',
            },
        ),
        migrations.AlterField(
            model_name='race',
            name='results',
            field=models.TextField(blank=True, help_text='List Event Results Here', null=True),
        ),
    ]
