# Generated by Django 3.0.2 on 2020-05-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0051_auto_20200525_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name_plural': ' About Us Page Entries'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name_plural': ' Home Page Entries'},
        ),
        migrations.AlterModelOptions(
            name='recruitmentpage',
            options={'verbose_name_plural': ' Recruitment Page Entries'},
        ),
        migrations.AlterModelOptions(
            name='sponsorpage',
            options={'verbose_name_plural': ' Sponsor Page Entries'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='full_gallery_link',
            field=models.URLField(default='', help_text='place google drive url here for the whole album'),
        ),
    ]
