# Generated by Django 3.0.2 on 2020-05-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0053_auto_20200531_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagebanners',
            options={'verbose_name_plural': '     Page Banners'},
        ),
        migrations.RenameField(
            model_name='pagebanners',
            old_name='about_banner',
            new_name='about_Banner',
        ),
        migrations.RenameField(
            model_name='pagebanners',
            old_name='recruitment_banner',
            new_name='recruitment_Banner',
        ),
        migrations.RenameField(
            model_name='pagebanners',
            old_name='schedule_banner',
            new_name='schedule_Banner',
        ),
        migrations.RenameField(
            model_name='pagebanners',
            old_name='sponsor_banner',
            new_name='sponsor_Banner',
        ),
    ]
