# Generated by Django 3.0.2 on 2020-05-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0054_auto_20200531_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebanners',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
