# Generated by Django 3.0.2 on 2020-05-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0056_pagebanners_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagebanners',
            name='image',
        ),
    ]
