# Generated by Django 3.0.2 on 2020-05-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0057_remove_pagebanners_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebanners',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
