# Generated by Django 3.0.2 on 2020-06-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0058_pagebanners_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagebanners',
            name='image',
        ),
        migrations.AddField(
            model_name='pagebanners',
            name='about_page_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pagebanners',
            name='recruitment_page_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pagebanners',
            name='schedule_page_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pagebanners',
            name='sponsor_page_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
