# Generated by Django 3.0.2 on 2020-06-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0060_auto_20200602_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadership',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='leadership',
            name='picture',
            field=models.ImageField(upload_to='leadership'),
        ),
    ]
