# Generated by Django 3.0.2 on 2020-06-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0062_event_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='public',
            field=models.BooleanField(default=False, help_text='When this is checked the race will be displayed on the website'),
        ),
        migrations.AlterField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=False, help_text='When this is checked the event will be displayed on the website'),
        ),
    ]
