# Generated by Django 3.0.2 on 2020-06-13 21:05

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0063_auto_20200608_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='images',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='rowingWebsiteApp.Picture'),
        ),
    ]
