# Generated by Django 3.0.2 on 2020-06-13 21:07

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0064_homepage_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', sortedm2m.fields.SortedManyToManyField(help_text=None, to='rowingWebsiteApp.Picture')),
            ],
            options={
                'verbose_name_plural': ' Home Page Gallery',
            },
        ),
    ]
