# Generated by Django 3.0.2 on 2020-06-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0065_homepagegallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='images',
        ),
    ]
