# Generated by Django 3.0.2 on 2020-06-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0066_remove_homepage_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageGallery',
        ),
    ]
