# Generated by Django 3.0.2 on 2020-06-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0068_homegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebanners',
            name='home_Banner',
            field=models.ImageField(default='', upload_to='banners'),
        ),
        migrations.AddField(
            model_name='pagebanners',
            name='home_page_title',
            field=models.CharField(default='Welcome To LSU Rowing', max_length=50),
        ),
        migrations.DeleteModel(
            name='HomeGallery',
        ),
    ]
