# Generated by Django 3.0.2 on 2020-06-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0070_auto_20200618_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(upload_to='template_photos'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image2',
            field=models.ImageField(upload_to='template_photos'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=models.ImageField(upload_to='template_photos'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='picture',
            field=models.ImageField(upload_to='leadership'),
        ),
        migrations.AlterField(
            model_name='pagebanners',
            name='about_Banner',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='pagebanners',
            name='home_Banner',
            field=models.ImageField(default='', upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='pagebanners',
            name='recruitment_Banner',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='pagebanners',
            name='schedule_Banner',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='pagebanners',
            name='sponsor_Banner',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='recruitmentpage',
            name='image',
            field=models.ImageField(default='none', help_text='This will be the image that gets displayed under the text', upload_to='recruitmentPagePictures'),
        ),
        migrations.AlterField(
            model_name='rower',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='sponsorpage',
            name='image',
            field=models.ImageField(upload_to='template_photos'),
        ),
    ]
