# Generated by Django 3.0.2 on 2020-06-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowingWebsiteApp', '0071_auto_20200618_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'ordering': ['my_order'], 'verbose_name_plural': ' About Us Page Entries'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'ordering': ['my_order'], 'verbose_name_plural': ' Home Page Entries'},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='image2',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homepage',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='full_gallery_link',
            field=models.URLField(blank=True, default='', help_text='place google drive url here for the whole album'),
        ),
    ]
